language: python
python:
  - "2.7"
  - "3.5"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
# command to run tests
script:
  - pytest